#Tags routes
###

GET http://localhost:3000/tags


#User routes
###

POST http://localhost:3000/users
Content-Type: application/json

{
    "user":{
        "username": "radu",
        "email": "radu@gmail.com",
        "password": "123"
    }
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "user":{
        "email": "radu@gmail.com",
        "password": "123"
    }
}

###

GET http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWR1IiwiZW1haWwiOiJyYWR1QGdtYWlsLmNvbSIsImlhdCI6MTY4MDI3NzMxOX0.eKOstdbWq4zzGHtMn7kwZ3R1YQlxvTacffUA9oB5xFU

###

PUT http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWR1IiwiZW1haWwiOiJyYWR1QGdtYWlsLmNvbSIsImlhdCI6MTY4MDI3NzMxOX0.eKOstdbWq4zzGHtMn7kwZ3R1YQlxvTacffUA9oB5xFU

{
    "user":{
        "bio": "M-am nascut langa Carpati"   
    }
}

#Article routes
###

POST http://localhost:3000/articles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWR1IiwiZW1haWwiOiJyYWR1QGdtYWlsLmNvbSIsImlhdCI6MTY4MDM5Mjc2OH0.9OGyPClrsQ725HZ9fSlctqP6GiQoetXl9tevMwKVLFc

{
    "article":{
        "title": "Example title 7",
        "description": "Lorem ipsum  something something something something something something",
        "body": "Even more filler text", 
        "tagList": ["vue", "golang", "php"]
    }
}

###

GET http://localhost:3000/articles?favorited=radu
Content-Type: application/json
Authorization: Berer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWR1IiwiZW1haWwiOiJyYWR1QGdtYWlsLmNvbSIsImlhdCI6MTY4MDM5Mjc2OH0.9OGyPClrsQ725HZ9fSlctqP6GiQoetXl9tevMwKVLFc


###

DELETE http://localhost:3000/articles/fooo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWR1IiwiZW1haWwiOiJyYWR1QGdtYWlsLmNvbSIsImlhdCI6MTY4MDM2NDg5NX0.HgR5zxhJ-6xzxgIW2bP4RBSpsNS0ZOvn_0ti2T6g6zg


###

PUT http://localhost:3000/articles/example-title-2-vkh42e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWR1IiwiZW1haWwiOiJyYWR1QGdtYWlsLmNvbSIsImlhdCI6MTY4MDM5Mjc2OH0.9OGyPClrsQ725HZ9fSlctqP6GiQoetXl9tevMwKVLFc

{
    "article":{
        "title": "Example title 3",
        "description": "Lorem ipsum  something something ",
        "body": "Some other filler text"    
    }
}


###

POST http://localhost:3000/articles/example-title-4-2xwdoj/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWR1IiwiZW1haWwiOiJyYWR1QGdtYWlsLmNvbSIsImlhdCI6MTY4MDM5Mjc2OH0.9OGyPClrsQ725HZ9fSlctqP6GiQoetXl9tevMwKVLFc


###

DELETE http://localhost:3000/articles/example-title-6-53rpor/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJyYWR1IiwiZW1haWwiOiJyYWR1QGdtYWlsLmNvbSIsImlhdCI6MTY4MDI3NzMxOX0.eKOstdbWq4zzGHtMn7kwZ3R1YQlxvTacffUA9oB5xFU
