###

GET http://localhost:3000/tags


###

POST http://localhost:3000/users
Content-Type: application/json

{
    "user":{
        "username": "radu",
        "email": "radu@gmail.com",
        "password": "123"
    }
}